server {
    listen 8080;
    server_name localhost;

    client_max_body_size 1M;
    client_timeout 10;
	session_timeout 20;

    error_page 404 /www/error/404.html;
    error_page 500 /www/error/500.html;

    location / {
        root www;
        index index.html;
        methods GET POST;
        autoindex on;
    }


    location /uploads {
        root www/uploads;
        methods GET POST DELETE;
        upload_dir www/uploads;
    }

    # CGI PYTHON
    location /cgi-bin/python {
        root cgi-bin/python;
        methods GET POST;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }

    # CGI PHP
    location /cgi-bin/php {
        root cgi-bin/php;
        methods GET POST;
        cgi_extension .php;
        cgi_path /usr/bin/php-cgi;
    }

    # SHELL EXEC
    location /cgi-bin/shell {
        root cgi-bin/shell;
        methods GET POST;
        cgi_extension .sh;
    }
}

server {
    listen 8080;
    server_name site2.local;

    client_max_body_size 1M;
    client_timeout 60;
	session_timeout 70;

    error_page 404 /www/error/404.html;
    error_page 500 /www/error/500.html;

    location / {
        root www;
        index index2.html;
        methods GET;
        autoindex on;
    }
}
