server {
    listen 8080;
    server_name localhost;

    client_max_body_size 1M;
    client_timeout 60;

    error_page 404 /www/error/404.html;
    error_page 500 /www/error/500.html;

    location / {
        root www;
        index index.html;
        methods GET POST;
        autoindex on;
    }

    location /uploads {
        root www/uploads;
        methods GET POST DELETE;
        upload_dir www/uploads;
    }

    # CGI PYTHON
    location /cgi-bin/python {
        root cgi-bin/python;
        methods GET POST;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }

    # CGI PHP
    location /cgi-bin/php {
        root cgi-bin/php;
        methods GET POST;
        cgi_extension .php;
        cgi_path /usr/bin/php-cgi;
    }

    # CGI PERL
    location /cgi-bin/perl {
        root cgi-bin/perl;
        methods GET POST;
        cgi_extension .pl;
        cgi_path /usr/bin/perl;
    }

    # CGI RUBY
    location /cgi-bin/ruby {
        root cgi-bin/ruby;
        methods GET POST;
        cgi_extension .rb;
        cgi_path /usr/bin/ruby;
    }

    # CGI NODE JS
    location /cgi-bin/node {
        root cgi-bin/node;
        methods GET POST;
        cgi_extension .js;
        cgi_path /usr/bin/node;
    }

    # CGI LUA
    location /cgi-bin/lua {
        root cgi-bin/lua;
        methods GET POST;
        cgi_extension .lua;
        cgi_path /usr/bin/lua;
    }

    # SHELL EXEC
    location /cgi-bin/shell {
        root cgi-bin/shell;
        methods GET POST;
        cgi_extension .sh;
    }
}
