#pragma once

#include <poll.h>
#include <vector>
#include <string>
#include <map>
#include <unistd.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/resource.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <fcntl.h>
#include <cstring>
#include <filesystem>
#include <csignal>
#include <algorithm>
#include <iostream>
#include <cerrno>
#include <signal.h>
#include <ctime>
#include <fstream>
#include <sstream>
#include <optional>
#include <set>
#include <time.h>
